### ISSUE TITLE
Require permission android.permission.WRITE_SETTINGS in Android 7.1.1, Patchlevel May, 2017

### ISSUE THREAD

**Issue by danielmorlock** [matejdro/TaskerTetherControl#1]
In Android 7.1.1 (Oxygen OS 4.1.5), Patchlevel May 2017, this is no more working. I get the following error:

```
21.07.09/E FIRE PLUGIN: Toggle Tethering / com.twofortyfouram.locale.intent.action.FIRE_SETTING: 3 bundle keys
21.07.09/E Toggle Tethering: plugin comp: com.matejdro.taskertethercontrol/com.matejdro.taskertethercontrol.TaskerReceiver
21.07.09/E add wait type Plugin1 time 7
21.07.09/E add wait type Plugin1 done
21.07.09/E add wait task
21.07.09/E Fehler: 2
21.07.09/E java.lang.reflect.InvocationTargetException: null
java.lang.SecurityException: com.matejdro.taskertethercontrol was not granted  this permission: android.permission.WRITE_SETTINGS.

**Comment by matejdro** [comment]
That means you did not install it into /system. Open plugin settings again and it should offer you a button to do so.

**Comment by danielmorlock** [comment]
Just figured out that since the last update, TRWP and su are gone ... I think this is the reason. First let me regain su than I will try as you suggest. Where can I find the plugin settings?

**Comment by matejdro** [comment]
Just edit wifi tethering action again (screen where you pick activate/deactivate tethering).

**Comment by danielmorlock** [comment]
Thank you!
