### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by carrsteven** [matejdro/TaskerTetherControl#2]
On the HTC U11 this app needs permission. ACCESS_WIFI_STATE.
![screenshot_20170626-195212](https://user-images.githubusercontent.com/29719321/27566170-fb928118-5aa8-11e7-85e7-08c98f1b8531.png)

**Comment by matejdro** [comment]
Can you test if this version work? 

[test.zip](https://github.com/matejdro/TaskerTetherControl/files/1104299/test.zip)

**Comment by carrsteven** [comment]
That works perfectly!

**Comment by matejdro** [comment]
Thanks for the report. I have also released this fix to play store now, so everyone will have it.
