### ISSUE TITLE
Android 8.1.0 failing to disconnect teather

### ISSUE THREAD

**Issue by ghost** [matejdro/TaskerTetherControl#4]
My Pixel 2 xl updated to 8.1.0 today. I noticed that tethering is still working, but untethering is failing with an error and so I end up with the phone untethered but due to the error the enable of wifi connection failed.  Ideally if the wifi is on when the tether plugin is called, it would be nice if wifi was re-enabled on un-tether.

Currently calling untether causes the tasker task to fail with an error exit

![screenshot_20180712-171901](https://user-images.githubusercontent.com/9016784/42646229-282cd73e-85f8-11e8-9cd8-a7ed5b75ea32.png)

**Comment by ghost** [comment]
I have fixed the immediate problem by switching off "beginner mode" and selecting "continue on error" on the untether call. The untether is clearly completing correctly, but throwing some error code, don't know how to display the error.

**Comment by matejdro** [comment]
Can you try opening task page and manually running it via play button on the bottom? It should display more descriptive error.

**Comment by ghost** [comment]
If I run it manually it works without error

**Comment by matejdro** [comment]
Huh that sound weird. What if you add shortcut to the task on your home screen and run it when screen is on?

**Comment by ghost** [comment]
Sorry I didn't get back earlier.
This shows an error when calling untether note that despite the error untether has completed as the icon has been removed from the status bar:-

![screenshot_20180721-183448](https://user-images.githubusercontent.com/9016784/43364880-41774fd2-931b-11e8-9280-b22ba726a1f5.png)

If I select continue after error on the untether

![screenshot_20180721-184636](https://user-images.githubusercontent.com/9016784/43364888-6c49cf1e-931b-11e8-8d12-a53eafd5e3be.png)

Then the untether completes correctly.

![screenshot_20180721-184651](https://user-images.githubusercontent.com/9016784/43364908-c64ca0fe-931b-11e8-998b-4fc8fc4d1569.png)


I cannot setup the disconnect task as an exit task for connect as I suspect that the error in untether stops the exit task from being called.

**Comment by matejdro** [comment]
But this error is for the Wifi On action, not the tether action, right?

**Comment by ghost** [comment]
Correct, however the problem is that the the "wifi on" is failing because the "wifi tether off" has returned with the wifi in a disconnected state.


run log looks like this for the "disconnect task"

![screenshot_20180801-182828](https://user-images.githubusercontent.com/9016784/43540397-8945c0d6-95bf-11e8-81c5-7e36ceac4e12.png)

What I have found is that if I add a "wait 15 seconds" after calling "tether off" then the "wifi on" will run correctly.

I would suggest that ideally the "tether off" should not exit with the wifi in a disconnected state.

**Comment by matejdro** [comment]
So is the problem in tether off or in wifi on?

**Comment by ghost** [comment]
It looks like the untether request to connectivity manager is operating asynchronously, and takes some time to complete after it is invoked. Ideally untether should wait for the operation to complete, I assume by registering a callback. However connectivity manager is a beast and figuring out what callback will be called looks difficult.
I generally think that the problem is livable with as long as it documented that untether may take some time to complete and during that time the status of the wifi is such that it may fail a wifi on request.
Another approach would  be to record the status of the wifi prior to the tether request and put it back into that state on an untether.

**Comment by ghost** [comment]
Some really good news! This problem has gone away at Android 9 (pie) so now we know where the problem was.
